In [5]:
import numpy as np
import cv2
import matplotlib.pyplot as plt
from scipy.ndimage import gaussian_laplace, gaussian_filter

/home/umityigitbsrn/miniconda3/envs/pytorch-stable/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [37]:
def _log_filter(kernel_size: tuple[int, int], sigma: float) -> np.ndarray:
    # laplacian of gradient filter

    # laplacian of gradient function (log)
    first_term = lambda arg: -1/(np.pi * (arg ** 4))
    second_term = lambda arg_01, arg_02, arg_03: 1 - (((arg_01 ** 2) + (arg_02 ** 2)) / (2 * (arg_03 ** 2)))
    exp_term = lambda arg_01, arg_02, arg_03: np.exp(-((arg_01 ** 2) + (arg_02 ** 2)) / (2 * (arg_03 ** 2)))
    log = lambda arg_01, arg_02, arg_03: first_term(arg_03) * second_term(arg_01, arg_02, arg_03) * exp_term(arg_01, arg_02, arg_03)

    x_len, y_len = kernel_size
    kernel = np.zeros(kernel_size)
    x_len_half = x_len // 2 # for -x_len_half to x_len_half
    y_len_half = y_len // 2 # same for y axis

    for x in range(-x_len_half, x_len_half + 1):
        for y in range(-y_len_half, y_len_half + 1):
            kernel[x + x_len_half, y + y_len_half] = log(x, y, sigma)
    kernel = -40 * kernel / log(0, 0, sigma)
    return kernel

def _conv_zero_cross(img: np.ndarray, kernel: np.ndarray) -> np.ndarray:
    # calculating output size
    output_height = img.shape[0] - kernel.shape[0] + 1
    output_width = img.shape[1] - kernel.shape[1] + 1
    output = np.zeros((output_height, output_width))

    for h_index in range(output_height):
        for w_index in range(output_width):
            output[h_index, w_index] = np.sum(img[h_index:(h_index+kernel.shape[0]), w_index:(w_index+kernel.shape[1])] * kernel)

    return output

def edge_detector():
    # load the image
    img = cv2.imread('./house.tif', cv2.IMREAD_GRAYSCALE)

    # compute laplacian of gaussian
    kernel = _log_filter((9, 9), 1.4).astype(int)
    print(kernel)
    print(np.sum(kernel))

    # find the zero crossing points
    # output = _conv_zero_cross(img, kernel)
    # print(output)
    # return output

In [38]:
edge_detector()

[[  0   0   0   1   2   1   0   0   0]
 [  0   1   3   4   5   4   3   1   0]
 [  0   3   5   3   0   3   5   3   0]
 [  1   4   3 -11 -23 -11   3   4   1]
 [  2   5   0 -23 -40 -23   0   5   2]
 [  1   4   3 -11 -23 -11   3   4   1]
 [  0   3   5   3   0   3   5   3   0]
 [  0   1   3   4   5   4   3   1   0]
 [  0   0   0   1   2   1   0   0   0]]
-36


In [ ]:
def Hough_transform():
    pass